name: Deploy

on:
  pull_request:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read
  pull-requests: write

env:
  AWS_REGION: us-east-1

jobs:
  validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - run: terraform fmt -check
      - run: terraform init -input=false
      - run: terraform validate

  plan:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    needs: validate
    defaults:
      run:
        working-directory: infra
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::468611216525:role/github-oidc-deployer
          aws-region: ${{ env.AWS_REGION }}

      - run: terraform init -input=false
      - run: terraform plan -no-color > plan.txt

      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: infra/plan.txt
          
#   build:
#     runs-on: ubuntu-latest
#     needs: validate
#     steps:
#       - uses: actions/checkout@v4

#       - uses: aws-actions/configure-aws-credentials@v4
#         with:
#           role-to-assume: arn:aws:iam::468611216525:role/github-oidc-deployer
#           aws-region: ${{ env.AWS_REGION }}

#       - name: Get ECR URL from Terraform
#         working-directory: infra
#         run: |
#           terraform init -input=false
#           echo "ECR=$(terraform output -raw ecr_repository_url)" >> $GITHUB_ENV

#       - name: Build & Push Image
#         working-directory: app
#         run: |
#           aws ecr get-login-password \
#             | docker login --username AWS --password-stdin $ECR
#           docker build -t app .
#           docker tag app:latest $ECR:latest
#           docker push $ECR:latest

#   deploy:
#     if: github.ref == 'refs/heads/main'
#     runs-on: ubuntu-latest
#     needs: build
#     defaults:
#       run:
#         working-directory: infra
#     steps:
#       - uses: actions/checkout@v4

#       - uses: aws-actions/configure-aws-credentials@v4
#         with:
#           role-to-assume: arn:aws:iam::468611216525:role/github-oidc-deployer
#           aws-region: ${{ env.AWS_REGION }}

#       - run: terraform init -input=false
#       - run: terraform apply -auto-approve
